### ISSUE TITLE
Channel-specific Triggers

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#965] opened 2019-06-18 18:06 UTC
Use case for me would be to not bother handling all of the required SMS opt-out keywords on other channels. `Cancel` is especially annoying. I can create a smart group for everyone who hasn't connected a channel besides SMS, but that still has the edge case of a user on SMS who connected something else, and I can't have edge cases like that. It would seem that a field similar to group, that allows users to pick channels, with empty being the default of all, would solve this.

**Comment by putorti** [comment] 2019-06-18 18:07
Looks like perhaps this is #207

**Comment by nicpottier** [comment] 2019-06-18 18:08
Yep, closing as a dupe of #207, agree this would be neat.

**Closed by nicpottier** 2019-06-18 18:08 UTC
