### ISSUE TITLE
Bottleneck on messages table for status field

### ISSUE THREAD

**Issue by johncordeiro** [rapidpro/rapidpro#1196] opened 2020-04-11 02:42 UTC
We've been experiencing long-running queries on database related to the status field of the Msg model. I've explored deeply what exact query is broken, and I've found this one: https://github.com/rapidpro/rapidpro/blob/master/temba/msgs/tasks.py#L144

This is for requeueing messages with statuses `Errored`. The query generated is this one:
```
SELECT "msgs_msg"."id",
       "msgs_msg"."uuid",
       "msgs_msg"."org_id",
       "msgs_msg"."channel_id",
       "msgs_msg"."contact_id",
       "msgs_msg"."contact_urn_id",
       "msgs_msg"."broadcast_id",
       "msgs_msg"."text",
       "msgs_msg"."high_priority",
       "msgs_msg"."created_on",
       "msgs_msg"."modified_on",
       "msgs_msg"."sent_on",
       "msgs_msg"."queued_on",
       "msgs_msg"."direction",
       "msgs_msg"."status",
       "msgs_msg"."response_to_id",
       "msgs_msg"."visibility",
       "msgs_msg"."msg_type",
       "msgs_msg"."msg_count",
       "msgs_msg"."error_count",
       "msgs_msg"."next_attempt",
       "msgs_msg"."external_id",
       "msgs_msg"."topup_id",
       "msgs_msg"."attachments",
       "msgs_msg"."connection_id",
       "msgs_msg"."metadata",
       "msgs_msg"."delete_reason"
FROM "msgs_msg"
LEFT OUTER JOIN "channels_channel" ON ("msgs_msg"."channel_id" = "channels_channel"."id")
WHERE ("msgs_msg"."direction" = 'O'
       AND "msgs_msg"."next_attempt" <= '2020-04-11 01:45:21.860872+00:00'
       AND "msgs_msg"."status" = 'E'
       AND NOT ("msgs_msg"."topup_id" IS NULL)
       AND NOT ("channels_channel"."channel_type" = 'A'
                AND "channels_channel"."channel_type" IS NOT NULL))
ORDER BY "msgs_msg"."created_on" ASC
LIMIT 5000
```

The `status` filter is the bottleneck in this case, as I don't see how getting errored messages in another way, I believe that we need a new index for that. Do you guys agree?

**Comment by rowanseymour** [comment] 2020-04-13 14:30
Hi @johncordeiro, can you share an explain? Here's one from our DB...

```
 Limit  (cost=16.59..16.59 rows=1 width=532) (actual time=308.920..308.920 rows=0 loops=1)
   ->  Sort  (cost=16.59..16.59 rows=1 width=532) (actual time=308.919..308.919 rows=0 loops=1)
         Sort Key: msgs_msg.created_on
         Sort Method: quicksort  Memory: 25kB
         ->  Nested Loop Left Join  (cost=0.85..16.58 rows=1 width=532) (actual time=308.912..308.912 rows=0 loops=1)
               Filter: (((channels_channel.channel_type)::text <> 'A'::text) OR (channels_channel.channel_type IS NULL))
               ->  Index Scan using msgs_msg_status on msgs_msg  (cost=0.57..8.26 rows=1 width=532) (actual time=308.912..308.912 rows=0 loops=1)
                     Index Cond: ((status)::text = 'E'::text)
                     Filter: ((topup_id IS NOT NULL) AND (next_attempt <= '2020-04-13 14:18:30.573878+00'::timestamp with time zone) AND ((direction)::text = 'O'::text))
                     Rows Removed by Filter: 199
               ->  Index Scan using channels_channel_pkey on channels_channel  (cost=0.28..8.30 rows=1 width=6) (never executed)
                     Index Cond: (msgs_msg.channel_id = id)
 Planning time: 0.527 ms
 Execution time: 308.971 ms
```

In this case tho unfortunately we aren't finding any rows.. so not sure how representative that is.
Part of the pain might be having to join on the channels table to exclude Android channels. Maybe there's a better way to encode "don't retry this message if it's errored".. using `next_attempt=NULL` or something.

**Comment by johncordeiro** [comment] 2020-04-13 16:16
hey @rowanseymour , this is the explain for the query:
```
 Limit  (cost=0.85..457591.04 rows=5000 width=638)
   ->  Nested Loop Left Join  (cost=0.85..34918342.74 rows=381546 width=638)
         Filter: (((channels_channel.channel_type)::text <> 'A'::text) OR (channels_channel.channel_type IS NULL))
         ->  Index Scan using msgs_msg_6d10fce5 on msgs_msg  (cost=0.57..32530245.33 rows=420162 width=638)
               Filter: ((topup_id IS NOT NULL) AND (next_attempt <= '2020-04-11 01:45:21.860872+00'::timestamp with time zone) AND ((direction)::text = 'O'::text) AND ((status)::text = 'E'::text))
         ->  Index Scan using channels_channel_pkey on channels_channel  (cost=0.28..5.67 rows=1 width=6)
               Index Cond: (msgs_msg.channel_id = id)
(7 rows)
```

If I try to run this query or use `EXPLAIN ANALYZE` on that, I never receive the result. But just by removing the filter `msgs_msg.status = 'E'` I receive the result immediately and I can run the `EXPLAIN ANALYZE` on it, this is the output:

```
 Limit  (cost=0.85..32812.26 rows=5000 width=638) (actual time=0.062..25.922 rows=5000 loops=1)
   ->  Nested Loop Left Join  (cost=0.85..695503924.11 rows=105985068 width=638) (actual time=0.061..23.839 rows=5000 loops=1)
         Filter: (((channels_channel.channel_type)::text <> 'A'::text) OR (channels_channel.channel_type IS NULL))
         Rows Removed by Filter: 845
         ->  Index Scan using msgs_msg_6d10fce5 on msgs_msg  (cost=0.57..32147157.94 rows=116711653 width=638) (actual time=0.053..10.046 rows=5845 loops=1)
               Filter: ((topup_id IS NOT NULL) AND (next_attempt <= '2020-04-11 01:45:21.860872+00'::timestamp with time zone) AND ((direction)::text = 'O'::text))
               Rows Removed by Filter: 4831
         ->  Index Scan using channels_channel_pkey on channels_channel  (cost=0.28..5.67 rows=1 width=6) (actual time=0.001..0.001 rows=1 loops=5845)
               Index Cond: (msgs_msg.channel_id = id)
 Planning time: 0.378 ms
 Execution time: 26.956 ms
(11 rows)
```

This is the final query that works, you can see that I just removed the condition `msgs_msg.status = 'E'`:
```
SELECT "msgs_msg"."id",
       "msgs_msg"."uuid",
       "msgs_msg"."org_id",
       "msgs_msg"."channel_id",
       "msgs_msg"."contact_id",
       "msgs_msg"."contact_urn_id",
       "msgs_msg"."broadcast_id",
       "msgs_msg"."text",
       "msgs_msg"."high_priority",
       "msgs_msg"."created_on",
       "msgs_msg"."modified_on",
       "msgs_msg"."sent_on",
       "msgs_msg"."queued_on",
       "msgs_msg"."direction",
       "msgs_msg"."status",
       "msgs_msg"."response_to_id",
       "msgs_msg"."visibility",
       "msgs_msg"."msg_type",
       "msgs_msg"."msg_count",
       "msgs_msg"."error_count",
       "msgs_msg"."next_attempt",
       "msgs_msg"."external_id",
       "msgs_msg"."topup_id",
       "msgs_msg"."attachments",
       "msgs_msg"."connection_id",
       "msgs_msg"."metadata",
       "msgs_msg"."delete_reason"
FROM "msgs_msg"
LEFT OUTER JOIN "channels_channel" ON ("msgs_msg"."channel_id" = "channels_channel"."id")
WHERE ("msgs_msg"."direction" = 'O'
       AND "msgs_msg"."next_attempt" <= '2020-04-11 01:45:21.860872+00:00'
       AND NOT ("msgs_msg"."topup_id" IS NULL)
       AND NOT ("channels_channel"."channel_type" = 'A'
                AND "channels_channel"."channel_type" IS NOT NULL))
ORDER BY "msgs_msg"."created_on" ASC
LIMIT 5000;
```

**Comment by nicpottier** [comment] 2020-04-13 16:24
This is definitely a problem we have seen and does need to be addressed. The query in question acts very differently when the DB is in a state of sending a ton of messages and starts taking a bunch of time.

The best fix here would be to figure out a perfect index that we could build that would essentially be handing off the maintaining of what messages may need to be retried to Postgres for maintenance. Just adding a status index is probably not the right solution.

Instead having a partial index on all messages that are pending / errored / queued while also making sure it doesn't include Android relayers sounds like the best option. That index size will grow and shrink with the number of messages which are candidates for retries and will be instant to query against since it will just be an index scan then.

Note that in general I feel that we should probably also move this task of "retrying" messages into courier as opposed to living in RapidPro as it feels very much more like the domain of courier. But that can happen after first figuring out the right index / query.

@johncordeiro if you want to work on figuring on the right partial index and query we'd definitely love a PR for this.

**Comment by johncordeiro** [comment] 2020-04-13 16:58
Ok, @nicpottier . I'm coordinating with @matmsa27 a PR for this. We'll share details soon to what path we want to go, so you can validate and we move forward with the Pull Request.

**Comment by matmsa27** [comment] 2020-04-17 02:50
Hi everybody.

We started a work investigation about problems with index and good practices on big databases. On this [documentation](https://www.postgresql.org/docs/11/sql-reindex.html) from PostgreSQL, we found that in bad performance cases in tables that have an index, can exist a suspect about the index is corrupted, so it is recommended to recreate all indexes from the table or recreate only the index with bad performance.

With a big database, we executed some initial tests. First, we recreated the index from the status column, and then we can do a query returned in a skillful time, and don't need change any condition on the query. After recreated the index, we executed the EXPLAIN ANALYSE and get these results.

```
Limit  (cost=2297901.05..2297904.17 rows=1247 width=753) (actual time=275391.711..275423.921 rows=5000 loops=1)
  ->  Sort  (cost=2297901.05..2297904.17 rows=1247 width=753) (actual time=275391.708..275414.005 rows=5000 loops=1)
      Sort Key: msgs_msg.created_on
      Sort Method: top-N heapsort  Memory: 4272kB
      ->  Nested Loop Left Join  (cost=13961.09..2297836.93 rows=1247 width=753) (actual time=86.993..274375.307 rows=446000 loops=1)
            Join Filter: (msgs_msg.channel_id = channels_channel.id)
            Rows Removed by Join Filter: 270325507
            Filter: (((channels_channel.channel_type)::text <> 'A'::text) OR (channels_channel.channel_type IS NULL))
            ->  Bitmap Heap Scan on msgs_msg  (cost=13961.09..2292512.15 rows=1253 width=753) (actual time=83.821..23593.656 rows=446000 loops=1)
                Recheck Cond: ((status)::text = 'E'::text)
                Filter: ((topup_id IS NOT NULL) AND (next_attempt <= '2020-04-11 01:45:21.860872+00'::timestamp with time zone) AND ((direction)::text = 'O'::text))
                Heap Blocks: exact=153959
                  ->  Bitmap Index Scan on msgs_msg_9acb4454  (cost=0.00..13960.78 rows=755761 width=0) (actual time=53.342..53.343 rows=446000 loops=1)
                      Index Cond: ((status)::text = 'E'::text)
               ->  Materialize  (cost=0.00..83.60 rows=240 width=20) (actual time=0.000..0.264 rows=607 loops=446000)
               ->  Seq Scan on channels_channel  (cost=0.00..82.40 rows=240 width=20) (actual time=0.881..3.013 rows=712 loops=1)
 Planning Time: 0.390 ms
 Execution Time: 275426.054 ms
(18 rows)

Time: 275676,522 ms (04:35,677)
```

Another interesting point to see is, the memory used to ordination is very near to limit(using 4mb), we increased to 50mb. With this adjust we can get the result on query with LIMIT = 5000 in approximately 01minute and 06 seconds.

We share the results with you to enrich more this discussion about the Rapidpro database. We are working on creating the manual index to a status column, that wraps the conditions about messages that didn't send.

Thanks a lot, guys.

**Comment by nicpottier** [comment] 2020-04-17 16:34
So be wary of taking anything away from these kinds of tests. Ill performing indexes will work much better after a rebuild and even better after you just load the big indexes into ram but that doesn't mean that is fixing anything, because under heavy load there will be lots of competition on what is using that ram, so performance will still suffer.

That is still a horrific explain plan.

I think the root of the problem here mostly has to do with Android channels having to be excluded. We need to get to a point where the query doesn't require any joins to get back what we want and once we have then we can build a partial index just for that query and have it execute instantly.

A few ideas down those line:
 * `next_attempt` may be the way we can differentiate with errored relayer messages and others.. we only need to retry messages that are errored with a next attempt and make sure never to set that on Android channel messages. I think it may be non-null right now which seems goofy anyways. Changing that to be null and never setting it on new messages seems like it would be a step in the right direction.
 
I think with just that we would be able to build a partial index that is perfect and things would always be quick.

**Comment by matmsa27** [comment] 2020-04-23 19:49
Hi Nic, ok, thanks for the direction. 

So, we separate a possible solution in 4 steps, involving the `next_attempt` can be null, msgs about the android channel type, the index and the condition to populate `next_attempt` when msgs have been failed on the android channel. The steps are:

1 – Make a migration to set `next_attempt` to can be null.
2 – Create a migration to get all msgs from the channel Android have been failed and set null. So the messages don't return in the query.
3 – To create an index using "direction" = 'O' and "status" = 'E' with "created_on ASC".
4 – Open a PR to change the condition to msgs about Android Channel when set values to next_attempt, in this case to channel android needs set the value to null.
	About this 4 step, can you help us with when specific we can update to adjust this?

What do you think? If everything is ok, can we move forward?

Another doubt, analyzing the query, we observed that the Android channel is already excluded from the query, so the problem would also not be the number of messages with error?

Thanks a lot, Nic.

**Comment by nicpottier** [comment] 2020-04-24 15:08
I believe for 3) you want that to be with `next_attempt` ASC not `created_on` ASC and only for values that have a `next_attempt`

The end goal here is to have a perfect index in the end, that is, an index that has only the values you want in it. Making `next_attempt` nullable and not using it for Android will get us there.

Not sure what you mean on 4). Do you mean changing the relayer to not account for the `next_attempt`? I don't think the relayer uses that at all already:
  https://github.com/rapidpro/android-channel/blob/master/app/src/main/java/io/rapidpro/androidchannel/SMSListener.java#L75

Perhaps @norkans7 can verify.

The problem with excluding Android via a query is that that is a join and you can't build an perfect index based on it, which is the point of this exercise.

**Comment by norkans7** [comment] 2020-04-24 17:36
I can confirm Android channel syncing does not use the `next_attempt` field
And even the retry mechanism for Android channels is on the Android app.

Currently `next_attempt` uses `auto_now_add` making it nullable will help to never write that for messages to android channels 

- The index can be on "direction" = 'O' and "status" = 'E' and next_attempt ASC WHERE next_attempt IS NOT NULL
I guess created_on ASC could be needed for ordering but I think the others would be enough for that particular query

- One other thing that could help is to not write the error status for messages on Android channel
since we will retry anyway from the app.
https://github.com/rapidpro/rapidpro/blob/master/temba/msgs/models.py#L848

**Comment by rowanseymour** [comment] 2021-05-24 18:48
Addressed in https://github.com/nyaruka/rapidpro/pull/3312 and https://github.com/nyaruka/rapidpro/pull/3317

**Closed by rowanseymour** 2021-05-24 18:48 UTC
