### ISSUE TITLE
Error when we try enable bulk sending with a Android channel already connected

### ISSUE THREAD

**Issue by supportticanalyse** [rapidpro/rapidpro#355] opened 2016-09-22 15:39 UTC
Hi,
i deployed the last version of Rapidpro. but when i connect Android channel and i try to enable bulk sending with external channel i have error: 

> KeyError at /channels/channel/claim_external/ 

https://rapidprodev.slack.com/files/pauline/F2E77DDJ4/sans_titre_1.png .

I have the same error with my Textit account and when i debug i have this: 

`Traceback (most recent call last):
  File "/opt/rapidpro/env/local/lib/python2.7/site-packages/django/core/handlers                                                                                        /base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/rapidpro/env/local/lib/python2.7/site-packages/django/utils/decorat                                                                                        ors.py", line 145, in inner
    return func(*args, **kwargs)
  File "/opt/rapidpro/env/local/lib/python2.7/site-packages/django/views/generic                                                                                        /base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/rapidpro/env/src/smartmin/smartmin/views.py", line 149, in dispatch
    return wrapper(request, *args, **kwargs)
  File "/opt/rapidpro/env/src/smartmin/smartmin/views.py", line 145, in wrapper
    return super(SmartView, self).dispatch(request, *args, **kwargs)
  File "/opt/rapidpro/env/local/lib/python2.7/site-packages/django/views/generic                                                                                        /base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "/opt/rapidpro/env/local/lib/python2.7/site-packages/django/views/generic                                                                                        /edit.py", line 215, in post
    return self.form_valid(form)
  File "/opt/rapidpro/temba/channels/views.py", line 1213, in form_valid
    config = {Channel.CONFIG_SEND_URL: data['url'], Channel.CONFIG_SEND_METHOD:                                                                                         data['method'], Channel.CONFIG_SEND_BODY: data['body']}
KeyError: u'body'
[22/Sep/2016 15:18:54] "POST /channels/channel/claim_external/?role=S&channel=6                                                                                         HTTP/1.1" 500 160861
`
I don't know if my methode is good but if i edit the ligne [https://github.com/rapidpro/rapidpro/blob/master/temba/channels/views.py#L1213](url) by deleting **Channel.CONFIG_SEND_BODY: data['body']**
it works. Could you tell me if my method is good or not? 
thanks in advance!

**Comment by ericnewcomer** [comment] 2016-09-22 16:41
Oy, this is nigh impossible to read.

I'm confused by this, bulk sending is only supposed to be supported with a Nexmo channel.
https://github.com/rapidpro/rapidpro/blob/master/temba/channels/views.py#L924

Can you write a clearer repro case with steps and the unexpected behavior?

**Comment by supportticanalyse** [comment] 2016-09-22 17:09
Ok,
I first of all connected a channel Android, then I tried to activate the "Bulk Sending" function by clicking on the button "Enable Bulk Sending". When I click on this button I go to a page that offers the possibility to either use Nexmo or External Channel. When I choose Exnernal Channel I go to a page where we must inform the URL of sending sms of external channel and the method (Post or Get or Put).
When we completed filling in the information and click on the button "SAVE" we have the error message 

> KeyError at /channels/channel/claim_external/

Shown in this image: https://rapidprodev.slack.com/files/pauline/F2E77DDJ4/sans_titre_1.png .

**Comment by ericnewcomer** [comment] 2016-09-22 17:13
Thanks this is helpful.

**Comment by ericnewcomer** [comment] 2016-09-22 17:19
It looks like the claim external form (only in the case of bulk senders) is not allowing a request body to be configured for the external channel. Is this something perhaps your team would contribute a fix and open a PR for?

**Comment by supportticanalyse** [comment] 2016-10-07 12:09
Hello
I apologize for this long silence. I do not know python programming (just a few notions) therefore to solve the problem I have just removed a portion of the line https://github.com/rapidpro/rapidpro/blob/master/temba/channels/views.py#L1207 that is to say, `,Channel.CONFIG_SEND_BODY: data ['body'].` I do not know if this is the right method but home seems to work for now. Do you think this is the best way? because if the code is there, I think he surely has a significance?
Best regards!

**Comment by ericnewcomer** [comment] 2016-10-24 16:03
I believe the solution is earlier in flow. The form itself needs to have all the necessary fields so that when it is submitted they can be saved appropriately.

**Comment by nicpottier** [comment] 2019-06-19 22:21
This looks like it is fixed (and tested as well). Closing.

**Closed by nicpottier** 2019-06-19 22:21 UTC
Labels: bug
