### ISSUE TITLE
Airtime action UI broken v6.0.8

### ISSUE THREAD

**Issue by KaitCrawford** [rapidpro/rapidpro#1447] opened 2021-03-01 17:41 UTC
When I try to create a new action to send airtime to a contact the edit flow view breaks.
The new action modal and entire canvas disappears along with any existing actions.
Refreshing the page brings back the canvas and existing actions.

The issue is reproducible in Chrome and Firefox with add blockers disabled.
I have checked and there is a DT One account connected to the workspace.

This error appears twice in the browser console when the issue occurs:
```
TypeError: Cannot read property 'endpoint' of undefined
    at new a (main.47030cd9.chunk.js:1)
    at yo (2.9c7f9e6f.chunk.js:2)
    at La (2.9c7f9e6f.chunk.js:2)
    at gs (2.9c7f9e6f.chunk.js:2)
    at lu (2.9c7f9e6f.chunk.js:2)
    at su (2.9c7f9e6f.chunk.js:2)
    at Js (2.9c7f9e6f.chunk.js:2)
    at 2.9c7f9e6f.chunk.js:2
    at t.unstable_runWithPriority (2.9c7f9e6f.chunk.js:2)
    at Vi (2.9c7f9e6f.chunk.js:2)
es @ 2.9c7f9e6f.chunk.js:2
n.callback @ 2.9c7f9e6f.chunk.js:2
fo @ 2.9c7f9e6f.chunk.js:2
os @ 2.9c7f9e6f.chunk.js:2
pu @ 2.9c7f9e6f.chunk.js:2
t.unstable_runWithPriority @ 2.9c7f9e6f.chunk.js:2
Vi @ 2.9c7f9e6f.chunk.js:2
du @ 2.9c7f9e6f.chunk.js:2
Js @ 2.9c7f9e6f.chunk.js:2
(anonymous) @ 2.9c7f9e6f.chunk.js:2
t.unstable_runWithPriority @ 2.9c7f9e6f.chunk.js:2
Vi @ 2.9c7f9e6f.chunk.js:2
Gi @ 2.9c7f9e6f.chunk.js:2
Yi @ 2.9c7f9e6f.chunk.js:2
$s @ 2.9c7f9e6f.chunk.js:2
enqueueSetState @ 2.9c7f9e6f.chunk.js:2
w.setState @ 2.9c7f9e6f.chunk.js:2
value @ main.47030cd9.chunk.js:1
(anonymous) @ main.47030cd9.chunk.js:1
fireEvent @ temba-components-5e509bdeb64725540036.js:1
handleOptionSelection @ temba-components-5e509bdeb64725540036.js:348
handleEvent @ temba-components-5e509bdeb64725540036.js:1
__boundHandleEvent @ temba-components-5e509bdeb64725540036.js:1
fireCustomEvent @ temba-components-5e509bdeb64725540036.js:1
handleSelection @ temba-components-5e509bdeb64725540036.js:54
handleClick @ temba-components-5e509bdeb64725540036.js:54
```

**Comment by ericnewcomer** [comment] 2021-03-01 18:06
I've not tried this on that version, but wanted to comment that I could not reproduce this on the tip. Perhaps this has since been fixed?

**Comment by moymoussan** [comment] 2021-03-04 19:06
The UI problem is fixed in this version, but... appears that DT1 changed their API with no advise, @rowanseymour was already checking this topic

**Comment by rowanseymour** [comment] 2021-04-02 14:25
All fixed now!

**Closed by rowanseymour** 2021-04-02 14:25 UTC

**Comment by KaitCrawford** [comment] 2021-04-12 15:16
Great to know! thanks Rowan
