### ISSUE TITLE
Can't install cffi and psycopg2-binary from pip-freeze.txt

### ISSUE THREAD

**Issue by douglaschalegre** [rapidpro/rapidpro#1257] opened 2020-07-07 18:49 UTC
Hi there! Im following the [docs](url)

I'm having trouble to install those specific versions that are required on the project. I've tried to install manually from pip install cffi and it works but when i go https://pastebin.com/Vh5pHcxE

**Comment by rowanseymour** [comment] 2020-07-07 20:18
Duplicate of https://github.com/rapidpro/rapidpro/issues/1258

**Closed by rowanseymour** 2020-07-07 20:18 UTC
