### ISSUE TITLE
Changing channels doesn't work / delayed

### ISSUE THREAD

**Issue by putorti** [rapidpro/rapidpro#901] opened 2019-03-26 17:43 UTC
<img width="248" alt="image" src="https://user-images.githubusercontent.com/82857/55020299-f4c53b80-4fcc-11e9-8377-ba6bfda8b4a0.png">

Both messages in this screen capture go to SMS, however adding the identifier is successful. I'm having the same problem with all channels. These flows did work in the old engine, and haven't been changed. Unclear how to proceed.

**Comment by putorti** [comment] 2019-03-26 17:45
Text account log:
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/82857/55020443-35bd5000-4fcd-11e9-8394-39650b559eb2.png">

Orphaned Facebook account log:

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/82857/55020505-55547880-4fcd-11e9-8eb3-3d2c6b3a5dc1.png">

**Comment by putorti** [comment] 2019-03-26 17:47
I am getting "You are the majority..." on Facebook, then when texting it back, I'm going to the original account. So there seems to be something odd on the timing of changing channels. It's not happening when I request it to happen, it may be happening after the end of the flow.

**Comment by nicpottier** [comment] 2019-03-26 17:59
Can you attach a minimal flow definition that reproduces this?

**Comment by putorti** [comment] 2019-03-26 18:35
Here's a few of the "Add" flows with a change channel.
[resistbot.json.zip](https://github.com/rapidpro/rapidpro/files/3009699/resistbot.json.zip)

Again if there's a RapidPro test environment I can use that has connections to Telegram, Twitter, Messenger, then I'd have a baseline environment to try to reproduce.

**Comment by nicpottier** [comment] 2019-03-26 18:39
This isn't really a repro case. We need a standalone flow that exhibits the behavior you are seeing. We don't see it ourselves so there is likely something unique that you are doing. You shouldn't need any kind of special environment for that, though you have all the tools you need to create one on the RapidBot env if you want.

**Comment by putorti** [comment] 2019-03-26 19:28
We put a trigger on this and it just doesn't respond:

[resistbot (1).json.zip](https://github.com/rapidpro/rapidpro/files/3009966/resistbot.1.json.zip)

<img width="890" alt="image" src="https://user-images.githubusercontent.com/82857/55027454-b4b98500-4fdb-11e9-9fff-c6477c89df08.png">

<img width="610" alt="image" src="https://user-images.githubusercontent.com/82857/55027473-bbe09300-4fdb-11e9-8eb7-f7caef302c12.png">

We've seen this behavior elsewhere of no response. No flow start, no catch-all, just dead.

**Comment by LisaBinIL** [comment] 2019-03-26 19:29
Well, I deleted everything in the flow so now it works.

**Comment by putorti** [comment] 2019-03-26 19:29
We'll try to isolate why it's happening, ever seen this before? This is our case locally:

<img width="674" alt="image" src="https://user-images.githubusercontent.com/82857/55027553-ecc0c800-4fdb-11e9-8ac1-b212323e0fc5.png">

**Comment by nicpottier** [comment] 2019-03-26 19:33
We tested this on our side and it works for us, so you need to figure out what your specific repro is. Also please keep these issues focused on a single issue. @chris-erickson can you help @putorti come up with a solid repro for this?

**Comment by putorti** [comment] 2019-03-26 19:40
We've got two staging instances, Resistbot Stage connected to Twilio/Telegram and MVP5 connected to Telegram but with -1 credits. Will re-file when we hit the dead end on a "cleaner" install.

**Comment by putorti** [comment] 2019-03-26 20:02
See if you can reproduce, for us, this flow hangs on phone number entry. Removing the channel switch works, adding it back causes it to hang again. Now I'm trying this in staging, but I'm running into another bug where the trigger just doesn't fire at all, no response. What qualifies as a solid repro? Should I remove all other flows in our staging environment?

[resistbot-2.json.zip](https://github.com/rapidpro/rapidpro/files/3010063/resistbot-2.json.zip)

**Comment by ericnewcomer** [comment] 2019-03-26 20:13
A good repro case would work following minimal specific steps on an empty account.

```
1) Import this flow
2) Add Telegram channel
3) Send keyword "channeltest"

Found: Blah
Expected: Blah
```
I took a stab, following the steps above. It looks like it is working as expected, but maybe I'm looking at the wrong thing? Another possibility is I'm testing against the current version of the flow engine (157)

<img width="597" alt="Screen Shot 2019-03-26 at 3 08 52 PM" src="https://user-images.githubusercontent.com/211652/55029857-1fb58c80-4fd9-11e9-95fa-3ccfc2e1bbec.png">

**Comment by nicpottier** [comment] 2019-06-11 22:11
Closing as I'm pretty sure this is fixed with latest. Feel free to reopen if not.

**Closed by nicpottier** 2019-06-11 22:11 UTC
