### ISSUE TITLE
Unclickable flow steps

### ISSUE THREAD

**Issue by codenonprofits** [rapidpro/rapidpro#624] opened 2017-08-30 02:24 UTC
Sometimes the rule or action editor/boxes do not pop up when clicking on flow steps, I think that the draggable component is causing that, because on the console appears that the flow is being saved instead of open the modal.

See below the log, and a video displaying the issue:

![issue-unclickable](https://user-images.githubusercontent.com/30082655/29852409-53f8b9be-8d10-11e7-82aa-befd3e0def85.gif)
![screen shot 2017-08-29 at 23 14 00](https://user-images.githubusercontent.com/30082655/29852551-1d7e84e4-8d11-11e7-8c9f-ad99400fb360.png)

**Comment by teehamaral** [comment] 2017-08-31 13:47
+1

**Comment by nicpottier** [comment] 2017-08-31 14:10
Can you reproduce this on TextIt.in? Would need a repro case to figure this out.

**Comment by teehamaral** [comment] 2017-08-31 14:44
@nicpottier yes, it's only happening sometimes with us, it looks like the drag is overlapping the click or something like how you can see on the gif

![simuling-on-textit](https://user-images.githubusercontent.com/5198870/29929047-dad06c08-8e40-11e7-8833-602ecdc0c36a.gif)

**Comment by codenonprofits** [comment] 2017-09-08 01:45
@nicpottier did you can to reproduce that on TextIt?

**Comment by nicpottier** [comment] 2017-09-08 14:35
I have not, no.

**Comment by ericnewcomer** [comment] 2017-09-29 16:05
The dragging is really sensitive in the editor, this is definitely something we should look into. Looks like that affects some people more than others. It probably depends on the sensitivity of your mouse tracking and the speed with which you click.

You can see in the gifs that you are definitely triggering the drag event (since you can see the pickup style changes) when you are intending to edit them.

**Comment by nicpottier** [comment] 2019-06-11 22:24
Addressed in new editor.

**Closed by nicpottier** 2019-06-11 22:24 UTC
