### ISSUE TITLE
Web Flow Runner

### ISSUE THREAD

**Issue by teehamaral** [rapidpro/rapidpro#582] opened 2017-06-13 19:37 UTC
Hey guys,

We are working on a web flow runner, the objective is to allow that any website can integrate with RapidPro using this solution. Our idea is to use WebSocket to work like communication way between websites and the RapidPro, a WebSocket server would be developed to listen to messages and dispatch them to website user and to a WS Channel on RapidPro.

We would like to know what do you think about that?

**Comment by nicpottier** [comment] 2017-06-13 19:57
Sounds like it could be interesting. This would just be a new channel type I take it?

**Comment by teehamaral** [comment] 2017-06-13 20:10
A new channel type on RapidPro, but would be necessary to also create a WebSocket server to work out. It would be the bridge between websites and RapidPro. We were thinking to use the Mage to do this functionality, but the web client need to connect with WebSocket Server, so, the Mage Server security would be broken :(

**Comment by nicpottier** [comment] 2017-06-13 20:11
Mage is not long for this world, so probably wouldn't recommend going that route. We've been working on a few new things including replacing all the sending and receiving with a GoLang service called Courier:
  https://github.com/nyaruka/courier

Could see that being the right choice for long running websocket connections.

**Comment by teehamaral** [comment] 2017-06-13 20:38
+1 Courier Project

So If I understood right Courier will support all RapidPro channels? So, we could add support to new WebSocket channel as well.

**Comment by nicpottier** [comment] 2017-06-13 20:41
Yes, that's right, courier will support all RapidPro channels. Right now we just have Twilio, Telegram and a few others but we'll implement the rest before long.

Big missing piece there is still the story for outbound, Courier is currently just inbound, but I'll prioritize us coming up with how messages get from RapidPro to Courier in the next week or two and implement outbound messaging.

**Comment by teehamaral** [comment] 2017-06-13 20:54
Super!

So, the idea is to remove courier service from RapidPro and add this responsibility to Courier microservice, making RapidPro faster, economizing server resources?

**Comment by nicpottier** [comment] 2017-06-13 20:58
Yes, long term the idea is to get messaging sending and receiving out of RapidPro and have Courier encapsulate the various protocols.. communication between the two will be largely in the form of queues with some db writes directly by courier as well.

I'm not super familiar with web sockets at the Go level, but I'm open to adding support for them to Courier as long as it is well encapsulated and doesn't cause too much complexity. Alternatively perhaps the right solution is to have something else manage all those active connections, much as Kannel does, and then have that be a exposed via a simple HTTP api that RapidPro/Courier talks. Depending on your timeline that may make more sense as Courier is a little ways out from us turning it on as a default.

**Comment by teehamaral** [comment] 2017-06-13 21:07
You had a great idea. I don't have many Go knowledge, but sure I'll study to contribute to this solution, mainly on WebSocket support.

**Comment by citizenrich** [comment] 2017-06-14 07:15
Just throwing something in here, that new web clients support HTTP2 server push. Support landed in Go 1.8, and can be done with stdlib. So, if the problem is avoiding polling by using websockets, then server push can do the same. Again, at least for somewhat recent browsers.

**Comment by ycleptkellan** [comment] 2017-12-04 17:22
Love this idea. It would be cool to support a configurable widget to run those flows through, e.g. https://support.flowxo.com/article/159-widget

**Comment by vctrferreira** [comment] 2017-12-07 19:52
Hey guys, I saw the current courier development state and I believe that it's a good time to start to design how it will work, maybe I can develop this feature in courier, what do you think about this @nicpottier?

**Comment by nicpottier** [comment] 2019-06-12 19:06
dupe of #695 .. same answer as that one. This is super straightforward to make happen but really doesn't need to be in RapidPro core.

**Closed by nicpottier** 2019-06-12 19:06 UTC
