### ISSUE TITLE
RapidPro UI nav items event listeners problem

### ISSUE THREAD

**Issue by ekeeya** [rapidpro/rapidpro#1335] opened 2020-09-07 05:08 UTC
As illustrated in the .gif below,   event listeners for the nav items seem to be active all the way to the section below the nav section
Could some one kindly help?
Thank you
![rapidpro-issue](https://user-images.githubusercontent.com/40180598/92350201-ec898f00-f0e0-11ea-83f9-f2c12c3828e4.gif)

**Comment by rowanseymour** [comment] 2020-09-07 14:36
Assuming this has been fixed in master because I can't reproduce it (there's a pretty significant UI refresh in master) and that'll be part of the 6.0 release at the start of November.

**Closed by rowanseymour** 2020-09-07 14:36 UTC

**Comment by ekeeya** [comment] 2020-09-07 14:42
Alright thanks @rowanseymour
